const swaggerAutogen = require("swagger-autogen")({
  openapi: "3.0.0",
});

const doc = {
  info: {
    version: "1.0.0",
    title: "Rydes API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "rydes-api-staging.herokuapp.com",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
  definitions: {
    addUser: {
      firstName: "John",
      lastName: "Doe",
      email: "johndoe@gmail.com",
      password: "password2021",
      phoneNumber: "+2348093635145",
      dateOfBirth: "1983-10-20",
      countryOfResidence: "Nigeria",
    },
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["./src/loaders/express.ts"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  // require("./src/app");
});
